/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'slug' : string,
  'readTime' : bigint,
  'excerpt' : string,
  'category' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Product {
  'amazonUrl' : string,
  'features' : Array<string>,
  'isBestChoice' : boolean,
  'cons' : Array<string>,
  'name' : string,
  'pros' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'rating' : bigint,
  'price' : string,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBestChoiceProducts' : ActorMethod<[], Array<Product>>,
  'getBlogPostBySlug' : ActorMethod<[string], BlogPost>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'submitContactForm' : ActorMethod<[ContactSubmission], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];