/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'slug' : IDL.Text,
  'readTime' : IDL.Nat,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'amazonUrl' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'isBestChoice' : IDL.Bool,
  'cons' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'pros' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBestChoiceProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitContactForm' : IDL.Func([ContactSubmission], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'slug' : IDL.Text,
    'readTime' : IDL.Nat,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'amazonUrl' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'isBestChoice' : IDL.Bool,
    'cons' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'pros' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBestChoiceProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([ContactSubmission], [], []),
  });
};

export const init = ({ IDL }) => { return []; };